### ISSUE TITLE
Html Report not showing graphs and mentioned starting time and duration time as "Unknown"

### ISSUE THREAD

**Issue by swedund** [cucumber/html-formatter#204]
Generated an HTML Report using [Cypress ](https://docs.cypress.io/guides/overview/why-cypress)with [badeball cucumber preprocessor](https://github.com/badeball/cypress-cucumber-preprocessor) using the execution mode as headless.
![image](https://user-images.githubusercontent.com/121144287/208811896-4d348157-53d6-41a0-a28c-1a945184aecd.png)

Issues:
1. Graphs are missing
2. Start Time and Duration Time shows as "Unknown"

Environments/Platform:
1. Cypress: 11.2.0
2. badeball Cypress Cucumber Preprocessor:12.0.1

**Comment by mpkorstanje** [comment]
This formatter consumes messages from the Cucumber message protocol. If information doesn't show up in the report there is a good chance it wasn't provided by `badeball/cypress-cucumber-preprocessor`. 

If you open the HTML report is an editor [you should see this template](https://github.com/cucumber/html-formatter/blob/251bd8e906f063cd99f52d43da54b5e6a933ba84/javascript/src/index.mustache.html#L15). The messages are stored in `window.CUCUMBER_MESSAGES`. Can you provide the `testRunStarted` and `testRunFinished` messages from that array?

**Comment by luke-hill** [comment]
Closing this as inactive. If you have an issue still @swedund could you double check the items mentioned and also check using the repo for the pre-processor
