### ISSUE TITLE
Mobile friendly report

### ISSUE THREAD

**Issue by tim-yao** [cucumber/html-formatter#237]
### 🤔 What's the problem you're trying to solve?

On mobile phones, the HTML report displayed ugly, and the text is too small. We often get test report notifications on the phone, so mobile readability is something I am looking for.

See the below example of a report displayed on the iPhone screen:

![Screenshot 2023-05-26 at 3 41 52 pm](https://github.com/cucumber/html-formatter/assets/31641325/af808768-48de-47a1-80a6-d6b8b8d761a8)

### ✨ What's your proposed solution?

The meta column layout on the top is not follow normal mobile responsive design, it's better to change to a vertical stack so it can have more space for the information.

Also, if the feature file path with the name is too long, make sure it's not breaking the layout like in the above screenshot.

### 📚 Any additional context?

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mpkorstanje** [comment]
Would be happy to take a pull request for this. Though I suspect it would require some changes in https://github.com/cucumber/react-components

**Comment by tim-yao** [comment]
Hi @mpkorstanje , I had a look at the react-components project in my local and I found that one has better mobile styles than the one in cucumber HTML formatter. Is HTML formatter project using the latest React components?

Screen shot from react components. You can see the feature file name wraps.
![Screenshot 2023-05-27 at 12 27 49 pm](https://github.com/cucumber/html-formatter/assets/31641325/d7ca94a7-16f5-4d44-bd6b-a1c45aedfe5d)

I also checked the report at https://reports.cucumber.io. That one is even better. But feature file name is not wrapped.

![Screenshot 2023-05-27 at 12 22 29 pm](https://github.com/cucumber/html-formatter/assets/31641325/3531b6fe-79c6-4f39-9e67-02ba4a9ed73e)
![Screenshot 2023-05-27 at 12 22 39 pm](https://github.com/cucumber/html-formatter/assets/31641325/660ac7f2-bf14-49a1-a24f-e82d147b6227)

**Comment by mpkorstanje** [comment]
>  Is HTML formatter project using the latest React components?

Yes. This project uses `"@cucumber/react-components": "21.0.1"` the latest version. There is some unreleased material in the repo but I don't see anything that immediately relates to this. Granted my knowledge of react is practically non-existent.

> Screen shot from react components. You can see the feature file name wraps.

Unfortunately I don't have a clue!
