### ISSUE TITLE
cucumber report is blank after test run is finished

### ISSUE THREAD

**Issue by saikabade** [cucumber/html-formatter#277]
Hello, am getting blank reports generated frequently after the test run is finished. I do see it happening more often with one of the feature files (Product Page feature) which has total 5 tests of which 2 are simple scenarios and 3 are scenario outlines (with 1,1 and 3 examples), the report generated is blank often with 2-3MB in file size . Upgraded from 9.3.0 to version 9.6.0 and no luck. Any suggestions or workarounds would be greatly appreciated!
When I open dev tool in the browser, I see the error: TypeError: e is not iterable
![image](https://github.com/cucumber/html-formatter/assets/24914556/60945af5-bc5d-4461-b788-51e0806fc5a1)

TIA

**Comment by saikabade** [comment]
mods@cucumber.io can someone please look into this issue?
@mattwynne @aslakhellesoy

**Comment by mpkorstanje** [comment]
Hi! Cucumber is an opensource project,  at present mostly ran and developed by mostly unpaid volunteers. So in principle you should  not expect that anyone will look at your issue.

You can however make it more likely by including sufficient details to help us understand the problem . Currently we have very little to go on other than that it doesn't work. 

Please have a look at https://stackoverflow.com/help/minimal-reproducible-example to help you understand this better.

Or if you have a sample of the report that you can publicly share that would be helpful too.
