### ISSUE TITLE
Package version is not bumped on changes

### ISSUE THREAD

**Issue by Dbuggerx** [cucumber/html-formatter#301]
### 👓 What did you see?

[Renovate bot updated `@cucumber/gherkin-utils`](6d2fd1f7e2f51f59913e46bc1ab1897579bcdf7f) but didn't bump the version of `@cucumber/html-formatter`. 

That causes inconsistencies, like when inspecting the `node_modules` of `@cucumber/cucumber` (version `10.6.0`), I see that its `@cucumber/html-formatter` version `21.3.1` still uses  `"@cucumber/gherkin-utils": "^8.0.0"`.

### ✅ What did you expect to see?

Each change should cause the version of `@cucumber/html-formatter` to change as well, making it possible for dependent packages to update it.

I'd suggest enabling [Renovate bot's `bumpversion`](https://docs.renovatebot.com/configuration-options/#bumpversion).

### 📦 Which tool/library version are you using?

@cucumber/cucumber: 10.6.0

### 🔬 How could we reproduce it?

1. Install `@cucumber/cucumber` (version `10.6.0`;
2. In its `node_modules`, inspect the `package.json` of `@cucumber/html-formatter`. It's on version `21.3.1`, but still uses `"@cucumber/gherkin-utils": "^8.0.0"` instead of `^9.0.0` .

**Comment by mpkorstanje** [comment]
The change you are looking at has not yet been released. The version will be bumped when this happens.

What is the underlying motivation to look at the specific version of `gherkin-utils`? Are you trying to solve a dependency convergence problem?

> Each change should cause the version of @cucumber/html-formatter to change as well, making it possible for dependent packages to update it.

That would make sense if every change was released. But currently the decision to release is still manual.

I also don't believe it is common for node package change their version number immediately after release as happens with Maven for example. But I would be happy to read about common processes that work otherwise.

**Comment by mpkorstanje** [comment]
Are you sure. When I look at the dependencies in `v21.3.1` `@cucumber/gherkin-utils@8.0.6` is used.

```
$ git checkout v21.3.1 
HEAD is now at a45a3ef Prepare release v21.3.1

$ npm ls --all --include dev | grep cucumber

$ npm ls --all --include dev | grep cucumber
@cucumber/html-formatter@21.3.1 /home/mpkorstanje/Projects/cucumber/html-formatter/javascript
├── @cucumber/compatibility-kit@15.0.0
├─┬ @cucumber/gherkin-streams@5.0.1
│ ├── @cucumber/gherkin@28.0.0 deduped
│ ├── @cucumber/message-streams@4.0.1 deduped
│ ├── @cucumber/messages@24.1.0 deduped
├─┬ @cucumber/gherkin-utils@8.0.6
│ ├─┬ @cucumber/gherkin@27.0.0
│ │ └─┬ @cucumber/messages@22.0.0
│ ├── @cucumber/messages@24.1.0 deduped
├─┬ @cucumber/gherkin@28.0.0
│ └── @cucumber/messages@24.1.0 deduped
├─┬ @cucumber/message-streams@4.0.1
│ └── @cucumber/messages@24.1.0 deduped
├─┬ @cucumber/messages@24.1.0
├─┬ @cucumber/query@12.0.2
│ ├── @cucumber/messages@24.1.0 deduped
├─┬ @cucumber/react-components@22.1.0
│ ├── @cucumber/gherkin-utils@8.0.6 deduped
│ ├─┬ @cucumber/messages@24.0.1
│ ├─┬ @cucumber/query@12.0.1
│ │ ├─┬ @cucumber/messages@19.1.4
│ ├── @cucumber/tag-expressions@6.1.0

```

**Comment by Dbuggerx** [comment]
You're right, I should've also looked at the [package-lock file](https://github.com/cucumber/html-formatter/blob/release/v21.3.1/javascript/package-lock.json#L454), my bad!
Sorry for the confusion, and thanks a lot for the support!
