### ISSUE TITLE
Are cli/bin entrypoints still required?

### ISSUE THREAD

**Issue by aurelien-reeves** [cucumber/html-formatter#4]
Are the cli/bin entrypoints still required? Or was it a way to make it easy to test acceptance criteria?

In ruby, `bin/cucumber-html-formatter` is not used with `cucumber-ruby`.
In javascript, `bin/cucumber-html-formatter.js` seems not to be used either.
In Java, `io.cucumber.htmlformatter.Main` seems not to be used either apart from acceptance tests.

If we find another way to properly test acceptance criteria for the html-formatter, is there any reason to keep those?

@aslakhellesoy @mpkorstanje @mattwynne @luke-hill @davidjgoss

**Comment by mpkorstanje** [comment]
I'm not seeing a `bin` directory in this project.

**Comment by mpkorstanje** [comment]
For java the `Main` class can be moved to `src/test`. And to make the acceptance tests work you can provide `-DclasspathScope=test`.

https://www.mojohaus.org/exec-maven-plugin/exec-mojo.html#classpathScope

**Comment by mpkorstanje** [comment]
For Java I don't think the acceptance tests can be done in another way because they depend on javascript being build.

**Comment by aurelien-reeves** [comment]
> For Java I don't think the acceptance tests can be done in another way because they depend on javascript being build.

I must say I don't see what the CLI has to do with the javascript build. The result from the javascript build are pre-processed before we call the CLI, and even before we run the acceptance tests

Does cucumber-jvm use the CLI from html-formatter?

**Comment by mpkorstanje** [comment]
Cucumber JVM does not use the main class. So it can be moved to it can be moved to `src/test`. 

However the acceptance tests do require the main method and I because the acceptance tests also require the javascript module to be build first, and copied over by make, I don't think should pull that out.

https://github.com/cucumber/html-formatter/blob/7937dffb4bc7b59103aa0ea591c966afd8dfe554/java/Makefile#L14-L16

We could make the unit tests work without requiring javascript to be build by adding some test stubs .

**Comment by aurelien-reeves** [comment]
> Cucumber JVM does not use the main class. So it can be moved to it can be moved to `src/test`.
> 
👌

> However the acceptance tests do require the main method and I because the acceptance tests also require the javascript module to be build first, and copied over by make, I don't think should pull that out.
> 
> https://github.com/cucumber/html-formatter/blob/7937dffb4bc7b59103aa0ea591c966afd8dfe554/java/Makefile#L14-L16
> 
> We could make the unit tests work without requiring javascript to be build by adding some test stubs .

I still cant see the relation between the javascript module build results, which has already been taken care of as part of the PR to move the build process into GHA ([#2](https://github.com/cucumber/html-formatter/pull/2/files#diff-7298dfadb58e7ef4739267940124286b2cce372236364ddaa65fec391bf7f14cR53)), and the main method.

The main method do not need the javascript files itself. It is just a method which take some data from stdin and call `MessagesToHtmlWriter`. Nothing more. The javascript files are required by `MessagesToHtmlWriter`, but not by the `main` method.

We could writte acceptance tests that works directly with `MessagesToHtmlWriter`.

It is exactly the same with ruby: the `bin/html-formatter` script only wraps stdin to the actual HtmlFormatter class. But cucumber-ruby do not use that `bin` entrypoint. So I guess the acceptance tests could validate the HtmlFormatter class itself directly rather than having an extra layer on top of it 🤔

**Comment by mpkorstanje** [comment]
> I still cant see the relation between the templates, which have already been taken care of as part of the PR to move the build process into GHA ([#2](https://github.com/cucumber/html-formatter/pull/2/files#diff-7298dfadb58e7ef4739267940124286b2cce372236364ddaa65fec391bf7f14cR53)), and the main method.

That would have been useful context to lead with. If you've removed the acceptance tests then the main method is no longer needed.

Though this looks all sorts of silly, I suppose that's what you are looking to fix?

https://github.com/cucumber/html-formatter/pull/2/files#diff-2373fff46f4bbeb13d234f705ed2031d9c9b083b8f6e880bb00b4a4220383b92R42

**Comment by aurelien-reeves** [comment]
> 
> That would have been useful context to lead with. If you've removed the acceptance tests from make then the main method is no longer needed.

Well, moving-out components from the monorepo into polyglot-repos imply to remove makefiles actually
But yeah, sorry. I could have link to the PR at least.

> 
> Though this looks all sorts of silly, I suppose that's what you are looking to fix?
> 
> https://github.com/cucumber/html-formatter/pull/2/files#diff-2373fff46f4bbeb13d234f705ed2031d9c9b083b8f6e880bb00b4a4220383b92R42

Well, this piece of code is ugly, but I am not sure I would have done better without the main method.
It is just that it looks like those bin/cli/main methods are there for the sole purpose of validating the html-formatter as part of the CI. If so, I suggest to get rid of those and to find another way to validate the html-formatters by instantiating the component as part of the rspec/junit/mocha test scripts

**Comment by aslakhellesoy** [comment]
None of the implementations need to ship a library with a command-line tool. It’s for testing only.

**Comment by mattwynne** [comment]
I've started some work towards this in #8

**Comment by mattwynne** [comment]
OK #8 is ready.

I'm kinda 😢 to see this go as I think that the idea of piping messages between binaries is a cool idea, but if it's not being used I guess we should rip it out, at least for now.
