### ISSUE TITLE
RELEASING and `make release` are missing

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/html-formatter#66]
### 🤔 What's the problem you've observed?

To release a project we can follow the instructions in `RELEASING` or more commonly run `make release`. Currently both are missing. I'd like to look into #65 but would be pointless without a way to release.

**Comment by aurelien-reeves** [comment]
Indeed `RELEASING` is missing.
But no `make release` is missing. There is no more such thing with the new release process based on GHA.

**Comment by mattwynne** [comment]
@aurelien-reeves FYI in https://github.com/cucumber/cucumber-parent we kept the `make release` command as a way to automate some of the steps that would otherwise be in `RELEASING.md`. See [here](https://github.com/cucumber/cucumber-parent/blob/main/Makefile#L39).

**Comment by mattwynne** [comment]
I've had a go at bringing some of the version management `make` stuff from the JVM project into this one, and making it polyglot, in https://github.com/cucumber/html-formatter/pull/72

It's more of a sketch than a proposal, I'd appreciate some feedback.

**Comment by aurelien-reeves** [comment]
Would there be other ways than using make for such things?

**Comment by mattwynne** [comment]
> Would there be other ways than using make for such things?

As I suggested in the PR, I think we could consider writing this as a Go CLI tool similar to the `changelog` one, if it stabilises enough. But as Rien has [said in that PR](https://github.com/cucumber/html-formatter/pull/72#issuecomment-1088060518), `make` is a good fit for an initial prototype.

**Comment by mpkorstanje** [comment]
Looks like this was fixed once we started using `polyglot-release`.
