### ISSUE TITLE
Java version not set to snapshot after release

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/html-formatter#69]
Looks like the version was set to 19.0.0 when making a release, but not set to 19.0.1-SNAPSHOT afterwards.  I just ran mvn install and now I've poluted my local cache.

https://github.com/cucumber/html-formatter/commit/b41c7785be35767c1c7f789456a47067cd6f9ef6#diff-d8225ebcfc11b480a6e4f54e183b67c3ead51635a167c106d928c2abf1f9ef66L12

Because this is a manual step easily forgotten having the make command from https://github.com/cucumber/html-formatter/issues/66 would be nice.

**Comment by aurelien-reeves** [comment]
We have to find a way to automate this rather than to relying on a manual step

**Comment by mpkorstanje** [comment]
Looks like this was fixed once we started using `polyglot-release`.
