### ISSUE TITLE
Remove Docker stuff?

### ISSUE THREAD

**Issue by mattwynne** [cucumber/html-formatter#7]
**What's the problem you've observed? 🤔**

There is some stuff in and around the html formatter to do with publishing a docker container that looks like legacy.

For example:

> The Docker image is automatically built on docker hub
https://github.com/cucumber/html-formatter/tree/main/javascript#docker-image

but https://hub.docker.com/repository/docker/cucumber/html-formatter was not updated for a year or so.

https://github.com/cucumber/html-formatter/blob/main/javascript/Dockerfile

https://github.com/cucumber/common/blob/82c4958886df6647a115ccf73df30ae09911a39b/compatibility-kit/scripts/cucumber-html-formatter#L7

**Do you have a proposal for making it better? 🦄**

We'd like to remove it, but we're not sure why it was there in the first place.

**Comment by aslakhellesoy** [comment]
The docker buld as well as the published images can be removed. The intent was to have a standalone exe that could be used to generate HTML from a measage stream.

But all the Cucumbers embedded the HTML formatter natively so it was never used.

**Comment by mattwynne** [comment]
I done this in https://github.com/cucumber/html-formatter/pull/8

**Comment by mattwynne** [comment]
- [x] Docker image/repository deleted.
- [ ]
